import React from 'react'
import Head from 'next/head'
import Main from '../components/Main'

export const getServerSideProps = async context => {
  const response = await fetch('https://fakestoreapi.com/products/')
  const TobeModified = await response.json()
  const data = TobeModified.map(item => ({
    ...item,
    rating: Math.floor(Math.random() * (5 - 1 + 1)) + 1,
  }))

  const responseCat = await fetch(
    'https://fakestoreapi.com/products/categories'
  )
  let categories = await responseCat.json()
  categories.unshift('All Products')
  return {
    props: { data, categories },
  }
}

export default function Home({ data, categories }) {
  return (
    <div className="bg-gray-100   ">
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main data={data} categories={categories} />
    </div>
  )
}
